# Theme
[general]
import = ["~/.config/alacritty/themes/rose-pine.toml"]

# Terminal color
[env]
TERM = "xterm-256color"

# Cursor configuration
[cursor.style]
shape = "Block"

[colors.cursor]
cursor = "0xcfcde2"
text = "0x000000"

# Mouse configuration
[mouse]
hide_when_typing = false

# Window configuration
[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 4
y = 4

# Font configuration
[font]
size = 12.0

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"
