#!/bin/bash

# Check if go is installed
if ! command -v go &> /dev/null; then
    echo "Go is not installed"
    exit 1
fi

# Check if an argument is passed and store it as the project name
# If no argument is passed, ask for the project name
if [[ $# -eq 1 ]]; then
    proj=$1
else
    read -p "Enter the name of the project: " proj
fi

# Check if directory already exists
if [[ -d $proj ]]; then
    echo -e "Directory \"$proj\" already exists"
    exit 1
fi

# Check if GITHUB_USERNAME is set and ask if it should be used
# If not, ask for the username
if [[ -z $GITHUB_USER ]]; then
    read -p "Enter your GitHub username: " username
else
    read -p "Do you want to use the existing GITHUB_USER ($GITHUB_USER)? [y/n]: " choice
    if [[ $choice == "y" || $choice == "Y" ]]; then
        username=$GITHUB_USER
    else
        read -p "Enter your GitHub username: " username
    fi
fi

# Create base project structure
mkdir -p $proj/{cmd/$proj,bin,pkg,internal,tests}

cd $proj

go mod init github.com/$username/$proj &> /dev/null

echo -e "package main\n\nfunc main() {\n}" > cmd/$proj/main.go

echo -e "# $proj" > README.md

echo -e "bin/\n.env" > .gitignore

echo -e "build:\n\t@go build -o bin/$proj cmd/$proj/main.go" > Makefile
echo -e "\nrun: build\n\t@bin/$proj" >> Makefile
